### ISSUE TITLE
无法完装

### ISSUE THREAD

**Issue by icemanpro** [slacrey/vue-aliplayer#10]
`npm install vue-aliplayer -S` 后，vue-aliplayer目录中，只有license、package.json、readme.md这三个文件

**Comment by snowdream** [comment]
+1

**Comment by developer-MaMingyang** [comment]
安装0.0.5版本的就可以了

**Comment by slacrey** [comment]
0.0.5版本已经修复

**Comment by developer-MaMingyang** [comment]
> 0.0.5版本已经修复

作者您好，我这边实测<=0.05的版本可以安装，但是0.05以后的版本无法安装，从npm/yarn下载下来后是一个空壳，希望我这个是个别现象，谢谢。
