### ISSUE TITLE
H5播放的时候没有控件 如播放按钮

### ISSUE THREAD

**Issue by allanwxl** [slacrey/vue-aliplayer#17]

**Comment by allanwxl** [comment]
![image](https://user-images.githubusercontent.com/15358736/58067871-a2199180-7bc1-11e9-94d8-7b234ba180f1.png)

**Comment by allanwxl** [comment]
添加默认配置https://help.aliyun.com/document_detail/62948.html?spm=a2c4g.11186623.4.6.73febf80RciuY3

**Comment by siyuewuyu** [comment]
vue里面在哪里添加默认配置的代码
