### ISSUE TITLE
不知道为什么我出现了2个video

### ISSUE THREAD

**Issue by shijunti19** [slacrey/vue-aliplayer#3]
我先进详情播放，然后退回列表，然后在进入详情他会出现2个video
![image](https://user-images.githubusercontent.com/5392211/34912070-d605d726-f911-11e7-9cec-c79ffd42b60e.png)
![image](https://user-images.githubusercontent.com/5392211/34912071-db7d61ec-f911-11e7-9d6a-424c87111eb9.png)
也会初始化2次

**Comment by weizhengda** [comment]
你好，这个问题您解决了么？我也遇到了这样的问题，还没解决。。

**Comment by shijunti19** [comment]
@weizhengda 哦解决了，修改他源代码，加个变量如果已经实例化就不要再实例化了！

**Comment by weizhengda** [comment]
哦，原来是这样，如何修改源代码呢？初学者，不太会，请指教，谢谢。。

**Comment by weizhengda** [comment]
@shijunti19

**Comment by EasonShen1989** [comment]
@shijunti19 在手机端点击播放，会进入全屏播放么？
